### ISSUE TITLE
kinda error 

### ISSUE THREAD

**Issue by JosephFM96** [sylviiu/ezytdl#120]
### Title: 
yt-dlp failed to complete [sendUpdates]

### Content: 
Unsupported URL: https://ww1.pornhoarder.tv/video/bryce-adams-anal-in-gas-station-bathroom/RlZMaHg4eTYyYThJN2l5TGttcWNMR1NxeGZZbFB3REFQa2JRVmRJS0pZND0=

### Stack: 
```py
Traceback (most recent call last):
  File "yt_dlp/YoutubeDL.py", line 1581, in wrapper
  File "yt_dlp/YoutubeDL.py", line 1716, in __extract_info
  File "yt_dlp/extractor/common.py", line 717, in extract
  File "yt_dlp/extractor/generic.py", line 2531, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://ww1.pornhoarder.tv/video/bryce-adams-anal-in-gas-station-bathroom/RlZMaHg4eTYyYThJN2l5TGttcWNMR1NxeGZZbFB3REFQa2JRVmRJS0pZND0=

```

### Below this line, please describe what caused this error.
----

**Comment by sylviiu** [comment]
This is not an error I can fix; the upstream project (yt-dlp) does not support this website.
