### ISSUE TITLE
erroe

### ISSUE THREAD

**Issue by Daniwx5** [sylviiu/ezytdl#121]
### Title: 
Internal error occurred!

### Content: 
{}

SyntaxError: Bad escaped character in JSON at position 21581
    at JSON.parse (<anonymous>)
    at C:\Users\asus\AppData\Local\Programs\ezytdl\resources\app.asar\util\currentVersion\pybridge.js:48:40
    at ChildProcess.exithandler (node:child_process:422:7)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)

(no stack)

### Stack: 
```js
- at module.exports (C:\Users\asus\AppData\Local\Programs\ezytdl\resources\app.asar\core\sendNotification.js:9:30)
- at module.exports (C:\Users\asus\AppData\Local\Programs\ezytdl\resources\app.asar\util\errorHandler.js:8:48)
- at process.<anonymous> (C:\Users\asus\AppData\Local\Programs\ezytdl\resources\app.asar\index.js:20:125)
- at process.emit (node:events:513:28)
- at emit (node:internal/process/promises:149:20)
- at processPromiseRejections (node:internal/process/promises:294:27)
- at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
```

### Below this line, please describe what caused this error.
----

**Comment by iamLightway** [comment]
Similar issue with me too
https://github.com/sylviiu/ezytdl/issues/122

**Comment by sylviiu** [comment]
> Similar issue with me too #122

This issue isn't related; yours has to do with a broken install of yt-dlp (which could have been caused by an earlier version of the app)

**Comment by sylviiu** [comment]
Sorry for never providing a response here; I haven't been able to figure this out for the life of me. I've had friends also report the exact same issue using very different versions of the app, so I'm at a loss. Will try to look further into it
