### ISSUE TITLE
error

### ISSUE THREAD

**Issue by erhansozen** [sylviiu/ezytdl#128]
### Title: 
yt-dlp failed to download https://rr1---sn-4g5edndk.googlevideo.com/videoplayback?expire=1703094683&ei=O9WCZYbWG63ti9oPpNyPwA4&ip=[ REDACTED ]&id=o-ABblUHZ92Lzd6hTU5iVIp6J9Gykqo3ykR8N1juwgWhXt&itag=140&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=rB&mm=31%2C26&mn=sn-4g5edndk%2Csn-c0q7lnse&ms=au%2Conr&mv=m&mvi=1&pl=19&gcr=at&initcwndbps=2361250&vprv=1&svpuc=1&mime=audio%2Fmp4&gir=yes&clen=4406499&dur=272.230&lmt=1698975822382825&mt=1703072456&fvip=5&keepalive=yes&fexp=24007246&c=IOS&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cgcr%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIhAIKJSh1dbpbIbvres7EO9UcGeVXwtIrFkRaF7PK-gEVoAiBU8EM26nni2RtAXUW52yXBIywYc-yHBbzeeAphjX7sTQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AAO5W4owRAIgKuJNRrVFILD5zALhq8r_c4fPlg75dT4c5nCTmNpLtQUCIDCzk2rv2Ns5FgG2d961ntN0kdnV2vyawPDVYbdmi3T0 [1]

### Content: 
[generic] videoplayback?expire=1703094683&ei=O9WCZYbWG63ti9oPpNyPwA4&ip=[ REDACTED ]&id=o-ABblUHZ92Lzd6hTU5iVIp6J9Gykqo3ykR8N1juwgWhXt&itag=140&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ==&mh=rB&mm=31,26&mn=sn-4g5edndk,sn-c0q7lnse&ms=au,onr&mv=m&mvi=1&pl=19&gcr=at&initcwndbps=2361250&vprv=1&svpuc=1&mime=audio/mp4&gir=yes&clen=4406499&dur=272: Requested format is not available. Use --list-formats for a list of available formats

### Stack: 
```py
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1581, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1737, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1796, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2901, in process_video_result
yt_dlp.utils.ExtractorError: [generic] videoplayback?expire=1703094683&ei=O9WCZYbWG63ti9oPpNyPwA4&ip=[ REDACTED ]&id=o-ABblUHZ92Lzd6hTU5iVIp6J9Gykqo3ykR8N1juwgWhXt&itag=140&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ==&mh=rB&mm=31,26&mn=sn-4g5edndk,sn-c0q7lnse&ms=au,onr&mv=m&mvi=1&pl=19&gcr=at&initcwndbps=2361250&vprv=1&svpuc=1&mime=audio/mp4&gir=yes&clen=4406499&dur=272: Requested format is not available. Use --list-formats for a list of available formats

```

### Below this line, please describe what caused this error.
----

(edit: removed IP instances in post)

**Comment by sylviiu** [comment]
What version of ezytdl are you using? What version of yt-dlp are you using?

**Comment by sylviiu** [comment]
closing for inactivity
