### ISSUE TITLE
Spotify playlist error

### ISSUE THREAD

**Issue by AdnanCudic** [sylviiu/ezytdl#130]
### Title: 
Internal error occurred!

### Content: 
{}

TypeError: Cannot read properties of undefined (reading 'items')
    at parse (C:\Users\Administrator\AppData\Local\Programs\ezytdl\resources\app.asar\util\platforms\spotify.js:27:79)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

(no stack)

### Stack: 
```js
- at module.exports (C:\Users\Administrator\AppData\Local\Programs\ezytdl\resources\app.asar\core\sendNotification.js:9:30)
- at module.exports (C:\Users\Administrator\AppData\Local\Programs\ezytdl\resources\app.asar\util\errorHandler.js:8:48)
- at process.<anonymous> (C:\Users\Administrator\AppData\Local\Programs\ezytdl\resources\app.asar\index.js:20:125)
- at process.emit (node:events:513:28)
- at emit (node:internal/process/promises:149:20)
- at processPromiseRejections (node:internal/process/promises:294:27)
- at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
```

### Below this line, please describe what caused this error.
----
Tried downloading a Spotify playlist that has 173 songs on it, it says 100/173 and Retrieving additional tracks above it. Seems like there's a limit of 100 songs?

**Comment by sylviiu** [comment]
There isn't a limit on songs for Spotify, it's that I've initially implemented pagination incorrectly. This issue has been fixed in nightly / dev builds, though! Try turning that on in settings, and manually performing an update check in the tray menu!

**Comment by sylviiu** [comment]
closing for inactivity
