### ISSUE TITLE
happens very often

### ISSUE THREAD

**Issue by ElementShadow** [sylviiu/ezytdl#138]
### Title: 
yt-dlp failed to download https://www.twitch.tv/videos/2004767552?filter=archives&sort=time [1]

### Content: 
[twitch:vod] 2004767552: Failed to download m3u8 information: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Stack: 
```py
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 4055, in urlopen
  File "yt_dlp\networking\common.py", line 114, in send
  File "yt_dlp\networking\_helper.py", line 204, in wrapper
  File "yt_dlp\networking\common.py", line 325, in send
  File "yt_dlp\networking\_requests.py", line 341, in _send
yt_dlp.networking.exceptions.HTTPError: HTTP Error 400: Bad Request

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 847, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 4087, in urlopen
yt_dlp.networking.exceptions._CompatHTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1570, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1705, in __extract_info
  File "yt_dlp\extractor\common.py", line 715, in extract
  File "yt_dlp\extractor\twitch.py", line 535, in _real_extract
  File "yt_dlp\extractor\common.py", line 1943, in _extract_m3u8_formats
  File "yt_dlp\extractor\common.py", line 1965, in _extract_m3u8_formats_and_subtitles
  File "yt_dlp\extractor\common.py", line 903, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 860, in _request_webpage
yt_dlp.utils.ExtractorError: [twitch:vod] 2004767552: Failed to download m3u8 information: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

```

### Below this line, please describe what caused this error.
----
i just trying to download source quality and this appear

**Comment by sylviiu** [comment]
Can't reproduce. Have you tried updating yt-dlp and trying again in the app?

**Comment by ElementShadow** [comment]
I think i had latest version 2.4.2
