### ISSUE TITLE
i got an error!

### ISSUE THREAD

**Issue by DJPilouDevelopersandmore** [sylviiu/ezytdl#147]
### Title: 
Error getting media info

### Content: 
There was an issue retrieving the info. Please try again.

### Stack: 
```js
- at module.exports (C:\Users\USER\AppData\Local\Programs\ezytdl\resources\app.asar\core\sendNotification.js:9:30)
- at wsprocess.<anonymous> (C:\Users\USER\AppData\Local\Programs\ezytdl\resources\app.asar\util\ytdlp.js:924:35)
- at wsprocess.emit (node:events:525:35)
- at wsprocess._complete (C:\Users\USER\AppData\Local\Programs\ezytdl\resources\app.asar\util\class\wsprocess.js:35:14)
- at Object.complete (C:\Users\USER\AppData\Local\Programs\ezytdl\resources\app.asar\util\class\wsprocess.js:68:109)
- at C:\Users\USER\AppData\Local\Programs\ezytdl\resources\app.asar\util\pythonBridge.js:127:39
- at Array.forEach (<anonymous>)
- at ChildProcess.<anonymous> (C:\Users\USER\AppData\Local\Programs\ezytdl\resources\app.asar\util\pythonBridge.js:125:76)
- at ChildProcess.emit (node:events:525:35)
- at maybeClose (node:internal/child_process:1091:16)
```

### Below this line, please describe what caused this error.
----

**Comment by sylviiu** [comment]
please provide the details of where this error originated. i cannot help unless that's provided
