### ISSUE TITLE
Spotify Playlist error

### ISSUE THREAD

**Issue by LouiLetsPlayPro** [sylviiu/ezytdl#159]
### Title: 
failed to retrieve filename of https://www.youtube.com/watch?v=uAYG46w1SCA: ERROR: HTTPSConnectionPool(host='www.youtube.com', port=443): Read timed out.

### Content: 
HTTPSConnectionPool(host='www.youtube.com', port=443): Read timed out.

### Stack: 
```js
- at module.exports (C:\Users\LO\AppData\Local\Programs\ezytdl\resources\app.asar\core\sendNotification.js:9:30)
- at PassThrough.<anonymous> (C:\Users\LO\AppData\Local\Programs\ezytdl\resources\app.asar\util\ytdlp.js:965:29)
- at PassThrough.emit (node:events:513:28)
- at addChunk (node:internal/streams/readable:324:12)
- at readableAddChunk (node:internal/streams/readable:297:9)
- at Readable.push (node:internal/streams/readable:234:10)
- at node:internal/streams/transform:182:12
- at PassThrough._transform (node:internal/streams/passthrough:46:3)
- at Transform._write (node:internal/streams/transform:175:8)
- at writeOrBuffer (node:internal/streams/writable:392:12)
```

### Below this line, please describe what caused this error.
----

**Comment by sylviiu** [comment]
Very sorry for getting back this late - that's the first time I've seen such an error. Does this still happen?
