### ISSUE TITLE
bug on windows

### ISSUE THREAD

**Issue by Ch0nts** [sylviiu/ezytdl#161]
### Title: 
Internal error occurred!

### Content: 
{}

TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Error'
    --- property 'error' closes the circle
    at JSON.stringify (<anonymous>)
    at process.<anonymous> (C:\Users\alvar\AppData\Local\Programs\ezytdl\resources\app.asar\index.js:20:159)
    at process.emit (node:events:513:28)
    at emit (node:internal/process/promises:149:20)
    at processPromiseRejections (node:internal/process/promises:294:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)

(no stack)

### Stack: 
```js
- at module.exports (C:\Users\alvar\AppData\Local\Programs\ezytdl\resources\app.asar\core\sendNotification.js:9:30)
- at module.exports (C:\Users\alvar\AppData\Local\Programs\ezytdl\resources\app.asar\util\errorHandler.js:8:48)
- at process.<anonymous> (C:\Users\alvar\AppData\Local\Programs\ezytdl\resources\app.asar\index.js:19:124)
- at process.emit (node:events:525:35)
- at process._fatalException (node:internal/process/execution:149:25)
```

### Below this line, please describe what caused this error.
----

**Comment by sylviiu** [comment]
super sorry for getting back so late! what exactly happened here? i can't help you troubleshoot without any sort of data as to what happened
