### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Pro-Coder-Boy** [sylviiu/ezytdl#163]
### Title: 
yt-dlp failed to download https://www.youtube.com/watch?v=gK_GA5A8k2Y [1]

### Content: 
unable to download video data: HTTP Error 403: Forbidden

### Stack: 
```py
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 3448, in process_info
  File "yt_dlp\YoutubeDL.py", line 3169, in dl
  File "yt_dlp\downloader\common.py", line 466, in download
  File "yt_dlp\downloader\http.py", line 369, in real_download
  File "yt_dlp\downloader\http.py", line 120, in establish_connection
  File "yt_dlp\YoutubeDL.py", line 4131, in urlopen
  File "yt_dlp\networking\common.py", line 115, in send
  File "yt_dlp\networking\_helper.py", line 208, in wrapper
  File "yt_dlp\networking\common.py", line 335, in send
  File "yt_dlp\networking\_requests.py", line 350, in _send
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden

```

### Below this line, please describe what caused this error.
----

**Comment by sylviiu** [comment]
i'd like to think this doesn't have to do with ezytdl, but rather yt-dlp and/or your network. if it works otherwise using another link or just on another day after not downloading anything for a while, you should be fine!
