### ISSUE TITLE
error after installing ffmpeg

### ISSUE THREAD

**Issue by BageRun** [sylviiu/ezytdl#170]
### Title: 
Internal error occurred!

### Content: 
{
    "errno": -4094,
    "code": "UNKNOWN",
    "syscall": "spawn"
}

Error: spawn UNKNOWN
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at spawn (node:child_process:783:9)
    at Object.execFile (node:child_process:359:17)
    at t.<computed> [as execFile] (node:electron/js2c/asar_bundle:2:2218)
    at C:\Users\VFVUser\AppData\Local\Programs\ezytdl\resources\app.asar\util\currentVersion\ffmpeg.js:23:27

(no stack)

### Stack: 
```js
- at module.exports (C:\Users\VFVUser\AppData\Local\Programs\ezytdl\resources\app.asar\core\sendNotification.js:9:30)
- at module.exports (C:\Users\VFVUser\AppData\Local\Programs\ezytdl\resources\app.asar\util\errorHandler.js:8:48)
- at process.<anonymous> (C:\Users\VFVUser\AppData\Local\Programs\ezytdl\resources\app.asar\index.js:20:125)
- at process.emit (node:events:513:28)
- at emit (node:internal/process/promises:149:20)
- at processPromiseRejections (node:internal/process/promises:294:27)
- at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
```

### Below this line, please describe what caused this error.
I don't know what this means, I just reset Windows, installed this, then installed ffmpeg, and after I opened it again, this text appeared
![1](https://github.com/sylviiu/ezytdl/assets/44798551/0659d4e9-6953-4372-ae01-e7cbd84eee2c)

**Comment by sylviiu** [comment]
very sorry for getting back to you late! hadn't had a lot of free time from work lately - does this issue persist? does the `%appdata%\ezytdl\ffmpeg-win64` path exist at all? and are you able to retry installing ffmpeg?
