### ISSUE TITLE
Fetching playlist

### ISSUE THREAD

**Issue by AyhamAl-Ali** [sylviiu/ezytdl#18]
### Title: 
Internal error occurred!

### Content: 
{}

TypeError: Cannot read properties of undefined (reading 'items')
    at parse (C:\Users\alali\AppData\Local\Programs\ezytdl\resources\app.asar\util\platforms\spotify.js:27:79)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

(no stack)

### Stack: 
```js
- at module.exports (C:\Users\alali\AppData\Local\Programs\ezytdl\resources\app.asar\core\sendNotification.js:9:30)
- at module.exports (C:\Users\alali\AppData\Local\Programs\ezytdl\resources\app.asar\util\errorHandler.js:8:48)
- at process.<anonymous> (C:\Users\alali\AppData\Local\Programs\ezytdl\resources\app.asar\index.js:20:125)
- at process.emit (node:events:513:28)
- at emit (node:internal/process/promises:149:20)
- at processPromiseRejections (node:internal/process/promises:294:27)
- at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
```

### Below this line, please describe what caused this error.
----
https://open.spotify.com/playlist/6dSz0AWxkgBfhlNBFyzqFf?si=81647a0c51714e3d

**Comment by sylviiu** [comment]
Originally, I didn't implement Spotify pagination properly (because I didn't have a playlist with enough tracks to trigger pagination), sorry!

This will be fixed by next nightly build.
