### ISSUE TITLE
macOS Internal Error Occurred

### ISSUE THREAD

**Issue by EchoPenguin792** [sylviiu/ezytdl#187]
### Title: 
Internal error occurred!

### Content: 
{
    "errno": -86,
    "code": "Unknown system error -86",
    "syscall": "spawn"
}

Error: spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at spawn (node:child_process:783:9)
    at Object.execFile (node:child_process:359:17)
    at t.<computed> [as execFile] (node:electron/js2c/asar_bundle:2:2218)
    at /Applications/ezytdl.app/Contents/Resources/app.asar/util/currentVersion/pybridge.js:44:27
    at new Promise (<anonymous>)
    at module.exports (/Applications/ezytdl.app/Contents/Resources/app.asar/util/currentVersion/pybridge.js:9:55)
    at Object.func (/Applications/ezytdl.app/Contents/Resources/app.asar/core/ipc/update/getVersion.js:7:67)
    at /Applications/ezytdl.app/Contents/Resources/app.asar/core/ipcHandler.js:26:25
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:2:88880)
    at EventEmitter.emit (node:events:513:28)

(no stack)

### Stack: 
```js
- at module.exports (/Applications/ezytdl.app/Contents/Resources/app.asar/core/sendNotification.js:9:30)
- at module.exports (/Applications/ezytdl.app/Contents/Resources/app.asar/util/errorHandler.js:8:48)
- at process.<anonymous> (/Applications/ezytdl.app/Contents/Resources/app.asar/index.js:20:125)
- at process.emit (node:events:513:28)
- at emit (node:internal/process/promises:149:20)
- at processPromiseRejections (node:internal/process/promises:294:27)
- at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
```

### Below this line, please describe what caused this error.
----
I opened the app and had this error pop up. I used to be able to open & use the app with no issue a few months ago. 

Looking at the other solved issues, I deleted the "bridge-darwin" and "ffmpeg-darwin64" folders but this didn't end up solving the problem.

Any ideas for a fix?

**Comment by EchoPenguin792** [comment]
Great, thank you so much for the response!
