### ISSUE TITLE
error

### ISSUE THREAD

**Issue by rettlesnake** [sylviiu/ezytdl#194]
### Title: 
Internal error occurred!

### Content: 
{}

TypeError: Cannot read properties of null (reading 'type')
    at /Applications/ezytdl.app/Contents/Resources/app.asar/util/ytdlp.js:2589:76
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

(no stack)

### Stack: 
```js
- at module.exports (/Applications/ezytdl.app/Contents/Resources/app.asar/core/sendNotification.js:9:30)
- at module.exports (/Applications/ezytdl.app/Contents/Resources/app.asar/util/errorHandler.js:8:48)
- at process.<anonymous> (/Applications/ezytdl.app/Contents/Resources/app.asar/index.js:20:125)
- at process.emit (node:events:513:28)
- at emit (node:internal/process/promises:149:20)
- at processPromiseRejections (node:internal/process/promises:294:27)
- at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
```

### Below this line, please describe what caused this error.
----

**Comment by sylviiu** [comment]
i haven't had too much free time to check issues, i apologize for getting back to you late!

could you explain what actually happened in this error? i can't help troubleshoot without that
