### ISSUE TITLE
internal error occured

### ISSUE THREAD

**Issue by b0ogdan** [sylviiu/ezytdl#196]
### Title: 
Internal error occurred!

### Content: 
{
    "errno": -86,
    "code": "Unknown system error -86",
    "syscall": "spawn"
}

Error: spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at spawn (node:child_process:783:9)
    at Object.execFile (node:child_process:359:17)
    at t.<computed> [as execFile] (node:electron/js2c/asar_bundle:2:2218)
    at /Applications/ezytdl.app/Contents/Resources/app.asar/util/currentVersion/pybridge.js:44:27
    at new Promise (<anonymous>)
    at module.exports (/Applications/ezytdl.app/Contents/Resources/app.asar/util/currentVersion/pybridge.js:9:55)
    at /Applications/ezytdl.app/Contents/Resources/app.asar/util/updateAvailable/pybridge.js:6:87
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

(no stack)

### Stack: 
```js
- at module.exports (/Applications/ezytdl.app/Contents/Resources/app.asar/core/sendNotification.js:9:30)
- at module.exports (/Applications/ezytdl.app/Contents/Resources/app.asar/util/errorHandler.js:8:48)
- at process.<anonymous> (/Applications/ezytdl.app/Contents/Resources/app.asar/index.js:20:125)
- at process.emit (node:events:513:28)
- at emit (node:internal/process/promises:149:20)
- at processPromiseRejections (node:internal/process/promises:294:27)
- at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
```

### Below this line, please describe what caused this error.
----

**Comment by UniqueName12345** [comment]
Are you using Norton? For some reason, Norton's starting to detect ezytdl as a virus

**Comment by b0ogdan** [comment]
Hi,
No, i am not using Norton.
I am on MacOS Monterey.

**Comment by Thisisauser6443** [comment]
Ditto, getting the same error on macOS Sonoma 14.5. Just wasn't sure how I'd get the logs

**Comment by sylviiu** [comment]
okay so sonoma is just a nightmare to deal with; i've had a few issue reports surrounding sonoma systems and i have absolutely no clue where to start because i don't have a mac 😭


> Are you using Norton? For some reason, Norton's starting to detect ezytdl as a virus
@UniqueName12345 this is unrelated (though valid approach), but i can definitely say you're not the only one; Norton, Bitdefender AND Windows Defender seems to have flagged the yt-dlp bridge (see #228)
