### ISSUE TITLE
MacOs Sonoma 14.2

### ISSUE THREAD

**Issue by bluesoftware** [sylviiu/ezytdl#204]
### Title: 
Internal error occurred!

### Content: 
{
    "errno": -86,
    "code": "Unknown system error -86",
    "syscall": "spawn"
}

Error: spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at spawn (node:child_process:783:9)
    at Object.execFile (node:child_process:359:17)
    at t.<computed> [as execFile] (node:electron/js2c/asar_bundle:2:2218)
    at /Applications/ezytdl.app/Contents/Resources/app.asar/util/pythonBridge.js:112:63

(no stack)

### Stack: 
```js
- at module.exports (/Applications/ezytdl.app/Contents/Resources/app.asar/core/sendNotification.js:9:30)
- at module.exports (/Applications/ezytdl.app/Contents/Resources/app.asar/util/errorHandler.js:8:48)
- at process.<anonymous> (/Applications/ezytdl.app/Contents/Resources/app.asar/index.js:20:125)
- at process.emit (node:events:513:28)
- at emit (node:internal/process/promises:149:20)
- at processPromiseRejections (node:internal/process/promises:294:27)
- at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
```

### Below this line, please describe what caused this error.
----

**Comment by sylviiu** [comment]
could you explain what actually happened here? i can't do anything without any sort of info

(i also don't use mac os personally, and have no idea what "error -86" is lol)
