### ISSUE TITLE
Sign in to confirm you're not a bot

### ISSUE THREAD

**Issue by Jzk07** [sylviiu/ezytdl#225]
### Title: 
yt-dlp failed to complete [sendUpdates]

### Content: 
[youtube] BR2jZqK6eSg: Sign in to confirm you’re not a bot. This helps protect our community. Learn more

### Stack: 
```py
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1626, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1761, in __extract_info
  File "yt_dlp\extractor\common.py", line 740, in extract
  File "yt_dlp\extractor\youtube.py", line 4366, in _real_extract
  File "yt_dlp\extractor\common.py", line 1263, in raise_no_formats
yt_dlp.utils.ExtractorError: [youtube] BR2jZqK6eSg: Sign in to confirm you’re not a bot. This helps protect our community. Learn more

```

### Below this line, please describe what caused this error.
I just tried to download a youtube video and then the error appears

**Comment by aidenszolosi** [comment]
I can confirm this bug is present on my client as well. I think potentially the bridge is outdated.

**Comment by sylviiu** [comment]
seems like this is related to yt-dlp itself; see [this issue on its repo](https://github.com/yt-dlp/yt-dlp/issues/10128)

**Comment by aidenszolosi** [comment]
> Still an issue, how to get around it?

In my experience, this issue is resolved with the latest versions of the bridge and ffmpeg. Try uninstalling and reinstalling or clearing cache files.
