### ISSUE TITLE
Sign in to confirm you’re not a bot.

### ISSUE THREAD

**Issue by willyrillyy** [sylviiu/ezytdl#231]
### Title: 
yt-dlp failed to download https://www.youtube.com/watch?v=TYOQQpmR-Rw [1]

### Content: 
[youtube] TYOQQpmR-Rw: Sign in to confirm you’re not a bot. This helps protect our community. Learn more

### Stack: 
```py
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1626, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1761, in __extract_info
  File "yt_dlp\extractor\common.py", line 740, in extract
  File "yt_dlp\extractor\youtube.py", line 4366, in _real_extract
  File "yt_dlp\extractor\common.py", line 1263, in raise_no_formats
yt_dlp.utils.ExtractorError: [youtube] TYOQQpmR-Rw: Sign in to confirm you’re not a bot. This helps protect our community. Learn more

```

### Below this line, please describe what caused this error.
----

**Comment by FaceCrap** [comment]
got the same thing just now.

**Comment by liaolingfen4** [comment]
got the same thing just now， how to solve it , any one who has idea?thank you so much
