### ISSUE TITLE
How do I get youtube to recognize my account using ezytdl?

### ISSUE THREAD

**Issue by H4LLL** [sylviiu/ezytdl#250]
### Title: 
yt-dlp failed to complete [sendUpdates]

### Content: 
[youtube] 0FRyWPOl2M0: Sign in to confirm your age. This video may be inappropriate for some users.

### Stack: 
```py
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1626, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1761, in __extract_info
  File "yt_dlp\extractor\common.py", line 741, in extract
  File "yt_dlp\extractor\youtube.py", line 4468, in _real_extract
  File "yt_dlp\extractor\common.py", line 1275, in raise_no_formats
yt_dlp.utils.ExtractorError: [youtube] 0FRyWPOl2M0: Sign in to confirm your age. This video may be inappropriate for some users.

```

----
I tried to download age-restricted videos from youtube using ezytdl, but my account was not recognized. How do I login to youtube from ezytdl?

**Comment by EsanLe** [comment]
![Uploading Screenshot 2024-12-04 at 1.31.07 PM.jpg…]()
