### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by singh-arsh9** [sylviiu/ezytdl#254]
### Title: 
Internal error occurred!

### Content: 
{}

Error: net::ERR_CONNECTION_RESET
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49935)
    at SimpleURLLoaderWrapper.emit (node:events:513:28)

(no stack)

### Stack: 
```js
- at module.exports (C:\Users\nonud\AppData\Local\Programs\ezytdl\resources\app.asar\core\sendNotification.js:9:30)
- at module.exports (C:\Users\nonud\AppData\Local\Programs\ezytdl\resources\app.asar\util\errorHandler.js:8:48)
- at process.<anonymous> (C:\Users\nonud\AppData\Local\Programs\ezytdl\resources\app.asar\index.js:20:125)
- at process.emit (node:events:513:28)
- at emit (node:internal/process/promises:149:20)
- at processPromiseRejections (node:internal/process/promises:294:27)
- at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
```

### Below this line, please describe what caused this error.
----

**Comment by singh-arsh9** [comment]
Sorry, Just needed to download FFMPEG From the settings.
