### ISSUE TITLE
path problem?

### ISSUE THREAD

**Issue by mrheat** [sylviiu/ezytdl#50]
### Title: 
yt-dlp failed to download https://soundcloud.com/600yearsirfalcon/sets/untitled-playlist [1]

### Content: 
unable to open for writing: [Errno 22] Invalid argument: '/Volumes/chia/nc/MUSIK/ytdl/mrheat777 (Likes)/ezytdl-SuTGArSzSlhccxTaDTTxFCeB.mp3.part'

### Stack: 
```py
Traceback (most recent call last):
  File "yt_dlp/utils/_utils.py", line 594, in sanitize_open
  File "yt_dlp/utils/_utils.py", line 1569, in __init__
OSError: [Errno 22] Invalid argument: '/Volumes/chia/nc/MUSIK/ytdl/mrheat777 (Likes)/ezytdl-SuTGArSzSlhccxTaDTTxFCeB.mp3.part'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp/downloader/http.py", line 260, in download
  File "yt_dlp/downloader/common.py", line 238, in wrapper
  File "yt_dlp/utils/_utils.py", line 5092, in __iter__
  File "yt_dlp/downloader/common.py", line 231, in error_callback
  File "yt_dlp/utils/_utils.py", line 5100, in report_retry
  File "yt_dlp/downloader/common.py", line 240, in wrapper
  File "yt_dlp/downloader/common.py", line 251, in sanitize_open
  File "yt_dlp/utils/_utils.py", line 596, in sanitize_open
OSError: [Errno 22] Invalid argument: '/Volumes/chia/nc/MUSIK/ytdl/mrheat777 (Likes)/ezytdl-SuTGArSzSlhccxTaDTTxFCeB.mp3.part'

```

### Below this line, please describe what caused this error.
----
selecting a path with spaces in name is a problem seems
also the folder is not created if not exist

**Comment by sylviiu** [comment]
Is this through a Mac system? Paths with spaces are functional on a Windows system, but I haven't done too much testing on Mac.

If the entire path exists and you attempt to download again, does it work?

**Comment by sylviiu** [comment]
closing due to no response

**Comment by mrheat** [comment]
Sorry didnt remember to look after it

Ok Mac OS Ventura the Volume "chia" is a normal APFS formatted second HDD. 
I tried mounting normal and without System following Ownership or User Rights, one can enable that, basically its a mount as User root. Same error. 

I also created the Path myself, its also bringing same error. 

What i will try is if it works on a Systems Boot Volume (/) directly in my User Folder.

**Comment by sylviiu** [comment]
I see. I'll have to look into it later, I'm out of town for a while; no access to any Mac systems. What version is this on?

**Comment by mrheat** [comment]
latest release version, i downloaded yesterday again to verify the error.
yes it happens if its external (not boot volume)
what wonders me because its all mounted under /Volumes/ ....
spaces i must say im not garantee they work, they should works, but learned to avoid them if bash skripts are involved
