### ISSUE TITLE
"code": "ERR_INVALID_ARG_TYPE"

### ISSUE THREAD

**Issue by murphy2mo** [sylviiu/ezytdl#57]
### Title: 
Internal error occurred!

### Content: 
{
    "code": "ERR_INVALID_ARG_TYPE"
}

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received null
    at stat (node:fs:1520:10)
    at t.stat (node:electron/js2c/asar_bundle:2:4626)
    at /Applications/ezytdl.app/Contents/Resources/app.asar/util/promisifiedFS/existsSync.js:4:8
    at new Promise (<anonymous>)
    at module.exports (/Applications/ezytdl.app/Contents/Resources/app.asar/util/promisifiedFS/existsSync.js:3:28)
    at promisified.<computed> [as existsSync] (/Applications/ezytdl.app/Contents/Resources/app.asar/util/promisifiedFS.js:36:26)
    at /Applications/ezytdl.app/Contents/Resources/app.asar/util/ytdlp.js:2177:32

(no stack)

### Stack: 
```js
- at module.exports (/Applications/ezytdl.app/Contents/Resources/app.asar/core/sendNotification.js:9:30)
- at module.exports (/Applications/ezytdl.app/Contents/Resources/app.asar/util/errorHandler.js:8:48)
- at process.<anonymous> (/Applications/ezytdl.app/Contents/Resources/app.asar/index.js:20:125)
- at process.emit (node:events:513:28)
- at emit (node:internal/process/promises:149:20)
- at processPromiseRejections (node:internal/process/promises:294:27)
- at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
```

### Below this line, please describe what caused this error.
----

**Comment by sylviiu** [comment]
Sorry for getting back so late. What version was this on? What caused the error?

**Comment by OrchidWarrior** [comment]
> Sorry for getting back so late. What version was this on? What caused the error?

latest DEV edition, i tries your fix before sending all issues ( as an answer to solution 63 but didn`t worked )

**Comment by sylviiu** [comment]
You are on a Mac system (I assume) from the error stack; I don't know much about these systems so please bare with me haha

Have you deleted the `~/Library/Application Support/ezytdl/bridge-darwin` folder?

**Comment by OrchidWarrior** [comment]
OS: Windows 11 Pro 22H2 22621.2134 :D DEV and Stable version got same error :<

**Comment by sylviiu** [comment]
Didn't realize you were a different person -- sorry about that lol.

What version are you trying to run? I still don't have much info I can work with here...

**Comment by sylviiu** [comment]
closing for inactivity
