### ISSUE TITLE
yt-dlp failed to complete [sendUpdates]

### ISSUE THREAD

**Issue by Mohsen-94** [sylviiu/ezytdl#77]
### Title: 
yt-dlp failed to complete [sendUpdates]

### Content: 
[twitch:vod] 1939158434: Video 1939158434 does not exist

### Stack: 
```py
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1567, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1702, in __extract_info
  File "yt_dlp\extractor\common.py", line 715, in extract
  File "yt_dlp\extractor\twitch.py", line 531, in _real_extract
  File "yt_dlp\extractor\twitch.py", line 401, in _download_info
yt_dlp.utils.ExtractorError: [twitch:vod] 1939158434: Video 1939158434 does not exist

```

### Below this line, please describe what caused this error.
----

**Comment by sylviiu** [comment]
this is likely something i cannot fix -- it does say that the video does not exist. does it show in browser?

**Comment by sylviiu** [comment]
closing to inactivity
