### ISSUE TITLE
yt-dlp failed to complete [sendUpdates]

### ISSUE THREAD

**Issue by Mohsen-94** [sylviiu/ezytdl#78]
### Title: 
Error getting media info

### Content: 
There was an issue retrieving the info. Please try again.

### Stack: 
```js
- at module.exports (C:\Users\asiri\AppData\Local\Programs\ezytdl\resources\app.asar\core\sendNotification.js:9:30)
- at wsprocess.<anonymous> (C:\Users\asiri\AppData\Local\Programs\ezytdl\resources\app.asar\util\ytdlp.js:924:35)
- at wsprocess.emit (node:events:525:35)
- at wsprocess._complete (C:\Users\asiri\AppData\Local\Programs\ezytdl\resources\app.asar\util\class\wsprocess.js:35:14)
- at Object.hook [as func] (C:\Users\asiri\AppData\Local\Programs\ezytdl\resources\app.asar\util\class\wsprocess.js:51:22)
- at C:\Users\asiri\AppData\Local\Programs\ezytdl\resources\app.asar\util\pythonBridge.js:212:104
- at Array.forEach (<anonymous>)
- at parse (C:\Users\asiri\AppData\Local\Programs\ezytdl\resources\app.asar\util\pythonBridge.js:212:89)
- at C:\Users\asiri\AppData\Local\Programs\ezytdl\resources\app.asar\util\pythonBridge.js:218:37
- at Array.forEach (<anonymous>)
- at Socket.<anonymous> (C:\Users\asiri\AppData\Local\Programs\ezytdl\resources\app.asar\util\pythonBridge.js:216:66)
- at Socket.emit (node:events:525:35)
- at addChunk (node:internal/streams/readable:324:12)
- at readableAddChunk (node:internal/streams/readable:293:11)
- at Readable.push (node:internal/streams/readable:234:10)
- at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

### Below this line, please describe what caused this error.
----

**Comment by sylviiu** [comment]
can you describe what you were doing to cause the error?

**Comment by sylviiu** [comment]
closing to inactivity
