### ISSUE TITLE
uh oh!

### ISSUE THREAD

**Issue by DeltaGazer** [sylviiu/ezytdl#8]
### Title: 
failed to retrieve filename of https://www.youtube.com/watch?v=h2b2KqOaU5E: ERROR: 'utf-8' codec can't decode byte 0xf3 in position 33: invalid continuation byte

### Content: 
'utf-8' codec can't decode byte 0xf3 in position 33: invalid continuation byte

### Stack: 
```js
- at module.exports (C:\Users\Delta\AppData\Local\Programs\ezytdl\resources\app.asar\core\sendNotification.js:8:26)
- at PassThrough.<anonymous> (C:\Users\Delta\AppData\Local\Programs\ezytdl\resources\app.asar\util\ytdlp.js:289:21)
- at PassThrough.emit (node:events:513:28)
- at addChunk (node:internal/streams/readable:324:12)
- at readableAddChunk (node:internal/streams/readable:297:9)
- at Readable.push (node:internal/streams/readable:234:10)
- at node:internal/streams/transform:182:12
- at PassThrough._transform (node:internal/streams/passthrough:46:3)
- at Transform._write (node:internal/streams/transform:175:8)
- at writeOrBuffer (node:internal/streams/writable:392:12)
```

### Below this line, please describe what caused this error.
----
pasted this and stuff broke :(
https://youtu.be/h2b2KqOaU5E

**Comment by sylviiu** [comment]
fixed in commit 263d571
