### ISSUE TITLE
"Error getting info" while trying to download a video

### ISSUE THREAD

**Issue by ppurplux** [sylviiu/ezytdl#81]
### Title: 
Error getting info

### Content: 
The path does not exist.

### Stack: 
```js
- at module.exports (C:\Users\purpl\AppData\Local\Programs\ezytdl\resources\app.asar\core\sendNotification.js:9:30)
- at C:\Users\purpl\AppData\Local\Programs\ezytdl\resources\app.asar\util\ytdlp.js:865:13
```

### Below this line, please describe what caused this error.
----
Just tried downloading a video and it gave me this error - tried with a few videos already, notably:
https://www.youtube.com/watch?v=P5OokD3gak0
https://www.youtube.com/watch?v=M5aGnrjRboQ
https://www.youtube.com/watch?v=kkStF_VOtgY
https://www.youtube.com/watch?v=xuFGvhq84eY
https://www.youtube.com/watch?v=drC7XQqWca8

P.S. - How do I use the browser connector extension? Thanks

**Comment by ppurplux** [comment]
Nevermind - I'm a moron and didn't realise I was on "Convert"

My question still stands, how do I use the extension?

**Comment by ppurplux** [comment]
Nevermind, found it in settings
