### ISSUE TITLE
ERROR REPORT

### ISSUE THREAD

**Issue by Rainman69** [sylviiu/ezytdl#84]
### Title: 
Error getting media info

### Content: 
There was an issue retrieving the info. Please try again.

### Stack: 
```js
- at module.exports (C:\Users\Admin\AppData\Local\Programs\ezytdl\resources\app.asar\core\sendNotification.js:9:30)
- at wsprocess.<anonymous> (C:\Users\Admin\AppData\Local\Programs\ezytdl\resources\app.asar\util\ytdlp.js:924:35)
- at wsprocess.emit (node:events:525:35)
- at wsprocess._complete (C:\Users\Admin\AppData\Local\Programs\ezytdl\resources\app.asar\util\class\wsprocess.js:35:14)
- at Object.hook [as func] (C:\Users\Admin\AppData\Local\Programs\ezytdl\resources\app.asar\util\class\wsprocess.js:51:22)
- at C:\Users\Admin\AppData\Local\Programs\ezytdl\resources\app.asar\util\pythonBridge.js:212:104
- at Array.forEach (<anonymous>)
- at parse (C:\Users\Admin\AppData\Local\Programs\ezytdl\resources\app.asar\util\pythonBridge.js:212:89)
- at C:\Users\Admin\AppData\Local\Programs\ezytdl\resources\app.asar\util\pythonBridge.js:218:37
- at Array.forEach (<anonymous>)
```

### Below this line, please describe what caused this error.
----

**Comment by sylviiu** [comment]
please provide the details of where this error originated. i cannot help unless that's provided
