### ISSUE TITLE
soundcloud

### ISSUE THREAD

**Issue by DeltaGazer** [sylviiu/ezytdl#9]
### Title: 
yt-dlp failed to complete [sendUpdates]

### Content: 
'NoneType' object has no attribute 'format'

### Stack: 
```js
- at module.exports (C:\Users\Delta\AppData\Local\Programs\ezytdl\resources\app.asar\core\sendNotification.js:9:30)
- at PassThrough.<anonymous> (C:\Users\Delta\AppData\Local\Programs\ezytdl\resources\app.asar\util\ytdlp.js:102:13)
- at PassThrough.emit (node:events:513:28)
- at addChunk (node:internal/streams/readable:324:12)
- at readableAddChunk (node:internal/streams/readable:297:9)
- at Readable.push (node:internal/streams/readable:234:10)
- at node:internal/streams/transform:182:12
- at PassThrough._transform (node:internal/streams/passthrough:46:3)
- at Transform._write (node:internal/streams/transform:175:8)
- at writeOrBuffer (node:internal/streams/writable:392:12)
```

### Below this line, please describe what caused this error.
----
https://soundcloud.com/user-924656928/sets/sketches?si=98cd353bee954830a64dcc3527dcfab2&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing

**Comment by sylviiu** [comment]
Modifying the error handler to show the Python trace in this situation points to YoutubeDL.py

```py
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1555, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1631, in __extract_info
  File "yt_dlp\extractor\common.py", line 705, in extract
  File "yt_dlp\extractor\common.py", line 609, in initialize
  File "yt_dlp\extractor\common.py", line 1335, in _get_login_info
  File "yt_dlp\extractor\common.py", line 1300, in _get_netrc_login_info
AttributeError: 'NoneType' object has no attribute 'format'
```

I've created an issue there at yt-dlp/yt-dlp#7369 for this.

**Comment by sylviiu** [comment]
turns out this has been fixed, i'll just build nightlies with yt-dlp nightly for stuff like this
