### ISSUE TITLE
Error getting media info

### ISSUE THREAD

**Issue by thegreatestgiant** [sylviiu/ezytdl#90]
### Title: 
Error getting media info

### Content: 
There was an issue retrieving the info. Please try again.

### Stack: 
```js
- at module.exports (C:\Users\seana\AppData\Local\Programs\ezytdl\resources\app.asar\core\sendNotification.js:9:30)
- at wsprocess.<anonymous> (C:\Users\seana\AppData\Local\Programs\ezytdl\resources\app.asar\util\ytdlp.js:924:35)
- at wsprocess.emit (node:events:525:35)
- at wsprocess._complete (C:\Users\seana\AppData\Local\Programs\ezytdl\resources\app.asar\util\class\wsprocess.js:35:14)
- at Object.hook [as func] (C:\Users\seana\AppData\Local\Programs\ezytdl\resources\app.asar\util\class\wsprocess.js:51:22)
- at C:\Users\seana\AppData\Local\Programs\ezytdl\resources\app.asar\util\pythonBridge.js:212:104
- at Array.forEach (<anonymous>)
- at parse (C:\Users\seana\AppData\Local\Programs\ezytdl\resources\app.asar\util\pythonBridge.js:212:89)
- at C:\Users\seana\AppData\Local\Programs\ezytdl\resources\app.asar\util\pythonBridge.js:218:37
- at Array.forEach (<anonymous>)
```

### Below this line, please describe what caused this error.
----
https://open.spotify.com/track/2EX0u5E7WnL27P12rBAdpG?si=acc410eddb0442b5

**Comment by sylviiu** [comment]
closing this issue to merge into #91; link is the same on both
