### ISSUE TITLE
yt-dlp failed to complete [sendUpdates]

### ISSUE THREAD

**Issue by thegreatestgiant** [sylviiu/ezytdl#91]
### Title: 
yt-dlp failed to complete [sendUpdates]

### Content: 
[DRM] The requested site is known to use DRM protection. It will NOT be supported.
       Please DO NOT open an issue, unless you have evidence that the video is not DRM protected

### Stack: 
```py
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1567, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1702, in __extract_info
  File "yt_dlp\extractor\common.py", line 715, in extract
  File "yt_dlp\extractor\unsupported.py", line 147, in _real_extract
yt_dlp.utils.ExtractorError: [DRM] The requested site is known to use DRM protection. It will NOT be supported.
       Please DO NOT open an issue, unless you have evidence that the video is not DRM protected

```

### Below this line, please describe what caused this error.
----
https://open.spotify.com/track/2EX0u5E7WnL27P12rBAdpG?si=acc410eddb0442b5

**Comment by sylviiu** [comment]
What version are you running? Works fine for me

![image](https://github.com/sylviiu/ezytdl/assets/95180094/d43c7722-6e46-484b-96cf-61ecff8e031c)

**Comment by sylviiu** [comment]
closing for inactivity
